// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct connection. Poolers such as Neon's `-pooler`
    // endpoint or pgBouncer cannot run them, so point DIRECT_DATABASE_URL at the
    // unpooled endpoint there; hosts whose pooled URL handles DDL need only
    // DATABASE_URL.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
